user: '${UID}:${GID}'
userns_mode: 'host'
services:
  server:
    image: docker.io/library/golang:latest
    environment:
      - 'MEDIAVOTE_PORT=8080'
      - 'MEDIAVOTE_ADMIN_KEY=1234'
      - 'MEDIAVOTE_ENV=${ENV}'
      - 'MEDIAVOTE_PG_DSN=postgres://pguser:pgpasswd@postgres:5432/pguser'
      - 'MEDIAVOTE_REDIS_ADDR=redis:6379'
      - 'MEDIAVOTE_REDIS_DB=0'
      - 'MEDIAVOTE_DEBUG=1'
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/myapp
      - ./testdata/gopath:/go
    working_dir: /usr/src/myapp
    command: ['go', 'run', 'main.go']
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpasswd
      - POSTGRES_DB=pguser
    ports:
      - 5432:5432
  redis:
    image: docker.io/library/redis:latest
    command: ['redis-server', '--loglevel', 'verbose']
    ports:
      - 6379:6379
